"""full_domain

Revision ID: 0895ed2369b7
Revises: 
Create Date: 2026-07-21 15:16:34.942385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0895ed2369b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=8), nullable=False),
    sa.Column('to_currency', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'as_of_date', name='uq_fx_pair_date')
    )
    op.create_index(op.f('ix_fx_rates_as_of_date'), 'fx_rates', ['as_of_date'], unique=False)
    op.create_table('internal_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_transactions_counterparty'), 'internal_transactions', ['counterparty'], unique=False)
    op.create_index(op.f('ix_internal_transactions_reference'), 'internal_transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_internal_transactions_value_date'), 'internal_transactions', ['value_date'], unique=False)
    op.create_table('reason_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reason_codes_code'), 'reason_codes', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parser_type', sa.String(length=32), nullable=False),
    sa.Column('is_webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('tolerance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_code'), 'sources', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('raw_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='raw_file_status'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('processing_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'sha256', name='uq_raw_source_sha')
    )
    op.create_index(op.f('ix_raw_files_source_id'), 'raw_files', ['source_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'MATCHED', 'FLAGGED', 'REJECTED', name='transaction_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_tx_source_external')
    )
    op.create_index(op.f('ix_transactions_counterparty'), 'transactions', ['counterparty'], unique=False)
    op.create_index(op.f('ix_transactions_raw_file_id'), 'transactions', ['raw_file_id'], unique=False)
    op.create_index(op.f('ix_transactions_source_id'), 'transactions', ['source_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_value_date'), 'transactions', ['value_date'], unique=False)
    op.create_index('ix_tx_source_value_date', 'transactions', ['source_id', 'value_date'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_code_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='flag_status'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_codes.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_reason_code_id'), 'flags', ['reason_code_id'], unique=False)
    op.create_index(op.f('ix_flags_status'), 'flags', ['status'], unique=False)
    op.create_index(op.f('ix_flags_transaction_id'), 'flags', ['transaction_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('internal_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['internal_transaction_id'], ['internal_transactions.id'], ),
    sa.ForeignKeyConstraint(['matched_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'internal_transaction_id', name='uq_match_pair')
    )
    op.create_index(op.f('ix_matches_internal_transaction_id'), 'matches', ['internal_transaction_id'], unique=False)
    op.create_index(op.f('ix_matches_transaction_id'), 'matches', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_transaction_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_internal_transaction_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_flags_transaction_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_status'), table_name='flags')
    op.drop_index(op.f('ix_flags_reason_code_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index('ix_tx_source_value_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_value_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_raw_file_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_raw_files_source_id'), table_name='raw_files')
    op.drop_table('raw_files')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_code'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reason_codes_code'), table_name='reason_codes')
    op.drop_table('reason_codes')
    op.drop_index(op.f('ix_internal_transactions_value_date'), table_name='internal_transactions')
    op.drop_index(op.f('ix_internal_transactions_reference'), table_name='internal_transactions')
    op.drop_index(op.f('ix_internal_transactions_counterparty'), table_name='internal_transactions')
    op.drop_table('internal_transactions')
    op.drop_index(op.f('ix_fx_rates_as_of_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###